import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.4";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const authHeader = req.headers.get("Authorization") ?? "";
    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_ANON_KEY")!,
      { global: { headers: { Authorization: authHeader } } }
    );

    const { data: { user }, error: authError } = await supabase.auth.getUser(
      authHeader.replace("Bearer ", "")
    );
    if (authError || !user) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const serviceClient = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    );

    // Get user role
    const { data: roleData } = await serviceClient
      .from("user_roles")
      .select("role")
      .eq("user_id", user.id)
      .single();

    const userRole = roleData?.role;
    if (!userRole || userRole === "owner") {
      return new Response(JSON.stringify({ error: "Owners transfer directly; agents/admins need approval" }), {
        status: 403, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const { enrollment_id, new_university_id, new_campus_id, new_course_id, new_intake_id } = await req.json();
    if (!enrollment_id || !new_university_id || !new_course_id) {
      return new Response(JSON.stringify({ error: "enrollment_id, new_university_id, new_course_id required" }), {
        status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Determine approver: agent → admin, admin → owner
    let approverId: string | null = null;
    let approverEmail: string | null = null;
    let approverName: string | null = null;

    if (userRole === "agent") {
      // Get user's admin
      const { data: profile } = await serviceClient
        .from("profiles")
        .select("admin_id")
        .eq("id", user.id)
        .single();
      if (profile?.admin_id) {
        approverId = profile.admin_id;
        const { data: adminProfile } = await serviceClient
          .from("profiles")
          .select("email, full_name")
          .eq("id", profile.admin_id)
          .single();
        approverEmail = adminProfile?.email || null;
        approverName = adminProfile?.full_name || null;
      }
    }

    if (userRole === "admin" || !approverId) {
      // Admin needs owner approval, or agent without admin also goes to owner
      const { data: owners } = await serviceClient
        .from("user_roles")
        .select("user_id")
        .eq("role", "owner")
        .limit(1);
      if (owners && owners.length > 0) {
        approverId = owners[0].user_id;
        const { data: ownerProfile } = await serviceClient
          .from("profiles")
          .select("email, full_name")
          .eq("id", owners[0].user_id)
          .single();
        approverEmail = ownerProfile?.email || null;
        approverName = ownerProfile?.full_name || null;
      }
    }

    if (!approverId || !approverEmail) {
      return new Response(JSON.stringify({ error: "No approver found" }), {
        status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Insert transfer request (code auto-generated by DB default)
    const { data: transferReq, error: insertError } = await serviceClient
      .from("transfer_requests")
      .insert({
        enrollment_id,
        requested_by: user.id,
        new_university_id,
        new_campus_id: new_campus_id || null,
        new_course_id,
        new_intake_id: new_intake_id || null,
        approver_id: approverId,
        status: "pending",
      })
      .select("id, code")
      .single();

    if (insertError) throw insertError;

    // Get context for the email
    const { data: requesterProfile } = await serviceClient
      .from("profiles")
      .select("full_name")
      .eq("id", user.id)
      .single();

    const { data: enrollment } = await serviceClient
      .from("enrollments")
      .select("student_id, universities!inner(name), courses!inner(name)")
      .eq("id", enrollment_id)
      .single();

    const { data: student } = enrollment?.student_id
      ? await serviceClient.from("students").select("first_name, last_name").eq("id", enrollment.student_id).single()
      : { data: null };

    const { data: newUni } = await serviceClient
      .from("universities")
      .select("name")
      .eq("id", new_university_id)
      .single();

    const { data: newCourse } = await serviceClient
      .from("courses")
      .select("name")
      .eq("id", new_course_id)
      .single();

    // Send email to approver
    await serviceClient.functions.invoke("send-transactional-email", {
      body: {
        templateName: "transfer-approval-code",
        recipientEmail: approverEmail,
        idempotencyKey: `transfer-code-${transferReq.id}`,
        templateData: {
          approverName: approverName || "Approver",
          requesterName: requesterProfile?.full_name || "A team member",
          studentName: student ? `${student.first_name} ${student.last_name}` : "Unknown Student",
          fromUniversity: (enrollment as any)?.universities?.name || "Unknown",
          fromCourse: (enrollment as any)?.courses?.name || "Unknown",
          toUniversity: newUni?.name || "Unknown",
          toCourse: newCourse?.name || "Unknown",
          code: transferReq.code,
        },
      },
    });

    return new Response(
      JSON.stringify({ success: true, transfer_request_id: transferReq.id }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (err) {
    return new Response(JSON.stringify({ error: err.message }), {
      status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
